---
title: "R Notebook"
output: html_notebook
---
# Email Kristal or Atal the new survey assignments

# If this is your first time running this script, you'll need to create your credential keys. University of Arizona emails block blastula from working so you need to use a personal account. 

# go to https://myaccount.google.com/security on your personal account, click 'App Passwords' under the 'Signing in to Google' section, and create a new password with 'Select App' -> Other.

# Then Create an app and give it a name. Enter your email address under "user" below. When running the code, the system will ask you to enter the password that  you created in Google.

# You only need to enter the password once. After that, comment the code below.
# Enter your email address under "user" below.
# When running the code, the system will ask you to enter the password that 
# you created in Google.
# You only need to enter the password once. After that, comment the code below.

#app password for dkangsim: qipr rszw mgvf rkpw

```{r}
create_smtp_creds_key(
   id = "gmail",
   user = "dkangsim@gmail.com",
   provider = "gmail",
   overwrite = TRUE
 )
```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
